#!/bin/bash

if [ $USER == "root" ];then
	user="sudo -H -u $SUDO_USER"
else
	user=""
fi


check_for_window() {
	attempts=40 # 20 seconds
	window_title="$1"
	while $attempts -gt 0; do
		while [ ! xdotool search --name $window_title ]; do
			((attempts--))
			sleep 0.25
			echo "Waiting for $window_title window to appear"

		done
	done
}	

#running=1

#echo "Checking for vpn connection..."
#while [ $running -eq 1 ];do
#        if [ $(piactl get connectionstate) == "Connected" ]; then
		wmctrl -s 3 && $user vivaldi-stable &
		check_for_window "vivaldi-stable"		
		sleep 1.5
		exit
 #       else
 #               echo "PIA is not connected"
 #               piactl connect
 #               sleep 0.5
 #       fi
#done   
